<?php

/**
 * Created by PhpStorm.
 * User: jcarfantan
 * Date: 07/06/2018
 * Time: 14:06
 */

namespace App\Model;

class BorrowKeychain {

    /**
     * @Id
     * @AutoGenerated
     */
    protected $id;

    /**
     * @NotNull
     */
    protected $idKeychain;
    protected $idUser;
    protected $dateRetour;

    /**
     * Many BorrowKeyChain have One Keychain.
     * @ManyToOne(targetEntity="Keychain", inversedBy="borrowKeychains")
     * @JoinColumn(name="idKeychain", referencedColumnName="id")
     */
    protected $keychain;

    /**
     * Many BorrowKeyChain have One User.
     * @ManyToOne(targetEntity="User", inversedBy="borrowKeychains")
     * @JoinColumn(name="idUser", referencedColumnName="id")
     */
    protected $user;

    public function getId() { return $this->id; }
    public function setId($id) { $this->id = $id; }

    public function setIdKeychain(int $idKeychain) { $this->idKeychain = $idKeychain; }
    public function getIdKeychain() { return $this->idKeychain; }

    public function setIdUser(int $idUser){ $this->idUser=$idUser; }
    public function getIdUser(){ return $this->idUser; }

    public function setDateRetour(\DateTime $dateRetour){ $this->dateRetour=$dateRetour; }
    public function getDateRetour(){ return $this->dateRetour; }

    public function getKeychain() { return $this->keychain; }
    public function setKeychain($keychain) { $this->keychain = $keychain; }

    public function getUser() { return $this->user; }
    public function setUser($user) { $this->user = $user; }

}
